config/routes.rb
Zassman::Application.routes.draw do
  resources :activities

  get "users/show"
  get 'tags/:tag', to: 'assets#index', as: :tag

  resources :assets do
    resources :comments, only: :create
    collection do
      get :search
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  match 'users/:id' => 'users#show', as: :user

  root to: 'assets#index'
  get 'about' => 'pages#about'

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  attr_accessible :box_link, :css, :invision_link, :name, :image, :image_remote_url, :tag_list
  acts_as_taggable
  acts_as_commentable
  
  belongs_to :user

  validates :name, presence: true
  validates :user_id, presence: true
  validates :tag_list, presence: true

  has_attached_file :image, styles: { medium: "320x240>"}
  validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 5.megabytes }

  searchkick

  def search_data
    as_json only: [:name, :tag_list]
  end

  def image_remote_url=(url_value)
    self.image = URI.parse(url_value) unless url_value.blank?
    super
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :search]
  # GET /assets
  # GET /assets.json
  def index
    if params[:tag]
      @assets = Asset.tagged_with(params[:tag]).page(params[:page]).per_page(15)
    else
      @assets = Asset.order("created_at desc").page(params[:page]).per_page(15)
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assets }
      format.js
    end
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
    @asset = Asset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/new
  # GET /assets/new.json
  def new
    @asset = current_user.assets.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @asset = current_user.assets.find(params[:id])
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = current_user.assets.new(params[:asset])

    respond_to do |format|
      if @asset.save
        track_activity @asset
        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
        format.json { render json: @asset, status: :created, location: @asset }
      else
        format.html { render action: "new" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.json
  def update
    @asset = current_user.assets.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        track_activity @asset
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset = current_user.assets.find(params[:id])
    @asset.destroy
    track_activity @asset

    respond_to do |format|
      format.html { redirect_to assets_url }
      format.json { head :no_content }
    end
  end

  def search
    # if params[:q]
    # query = params[:q]
    # @search = Asset.search do
    # fulltext query
    # end
    # @search_results = @search.results
    # end

    if params[:q].present?
      @search_results = Asset.search(params[:q], page: params[:page])
    else
      @search_results = Asset.all.page params[:page]
    end
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_asset.html.erb
<div class="box">
  <%= link_to (image_tag asset.image(:medium)), asset %>
  <p class="name">
    <%= asset.name %>
  </p>
  <p>
    <strong>
      Posted by <%= link_to asset.user.name, asset.user %>
    </strong>
  </p>
  <% if current_user == asset.user %>
    <p>
      <%= link_to 'Edit', edit_asset_path(asset) %>
      <%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
</div>

app/views/assets/_form.html.erb
<%= simple_form_for(@asset, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <div class="form-inputs">
    <%= f.input :image, label: "Upload an image" %>
    <%= f.input :image_remote_url, label: "or enter a URL" %>
    <%= f.input :name %>
    <%= f.input :box_link %>
    <%= f.input :invision_link %>
    <%= f.input :css, as: :text, input_html: { rows: "10" } %>
    <%= f.input :tag_list, as: :text, label: "Tags (separated by commas)", input_html: { rows: "3" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<h1>Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<div class="jumbotron tk-proxima-nova">
  <div class="container">
    <h1>Zendesk Creative Assets</h1>
    <p><b>Airy</b>, <b>Humble</b>, <b>Charming</b>, and <b>Uncomplicated</b>. These are the words that symbolize what the Zendesk Creative Department tries to create daily.</p>
  </div>
</div>

<div class="container">
  <div id="assets">
    <%= render @assets %>
  </div>

  <%= will_paginate @assets %>
</div>

app/views/assets/index.js.erb
$boxes = $('<%= j render(@assets) %>')

$('#assets').append( $boxes ).imagesLoaded( function(){
    $('#assets').masonry( 'reload');
});
<% if @assets.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate(@assets) %>');
<% else %>
    $('.pagination').remove();
<% end %>

app/views/assets/new.html.erb
<div class="container bodypadding">
  <h1 class="tk-proxima-nova">New asset</h1>

  <%= render 'form' %>

  <%= link_to 'Back', assets_path %>

</div>

app/views/assets/search.html.erb
<div class="container bodypadding">
  <h1 class="tk-proxima-nova">Search Results</h1>

  <% @search_results.each do |search| %>
    <div class="results">
      <div class="box">
        <%= link_to (image_tag search.image(:medium)), asset_path(search.id) %>
      </div>
    </div>

  <% end %>
</div>

app/views/assets/show.html.erb
<div class="container bodypadding">
  <div class="row">
  <div class="span6 offset3">
    <div class="well">

      <p id="notice"><%= notice %></p>
      <%= image_tag @asset.image %>
      <p>
        <b>Box link:</b>
        <%= @asset.box_link %>
      </p>

      <p>
        <b>Invision link:</b>
        <%= @asset.invision_link %>
      </p>

      <p>
        <b>Css:</b>
        <%= @asset.css %>
      </p>

      <p>
        <b>Name:</b>
        <%= @asset.name %>
      </p>

      <p>
        Tags: <%= raw @asset.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
      </p>

      <% if current_user == @asset.user %>
        <%= link_to 'Edit', edit_asset_path(@asset) %> |
      <% end %>
      <%= link_to 'Back', assets_path %>
    </div>
  </div>
</div>

<div class="row">
  <div class="span6 offset3">
    <div class="comments">
      <% @asset.root_comments.each do |comment|%>
        <div class="comment">
          <h3><%= link_to comment.user.name, comment.user %> said:</h3>
          <p><%= comment.body %></p>
          <small><%= comment.created_at.strftime("Posted on %m-%e-%y %H:%M") %></small>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="span6 offset3">
    <div class="comment_form">
      <%= simple_form_for Comment.new, url: asset_comments_path(@asset) do |f| %>
        <%= f.input :body, label: "Comment", input_html: { rows: "3" } %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

</div>