config/routes.rb
Zassman::Application.routes.draw do
  resources :activities

  get "users/show"
  get 'tags/:tag', to: 'assets#index', as: :tag

  resources :assets do
    resources :comments, only: :create
    collection do
      get :search
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  match 'users/:id' => 'users#show', as: :user

  root to: 'assets#index'
  get 'about' => 'pages#about'

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="footer">
    <small>
      <%= link_to "Zendesk", "http://zendesk.com" %>
      by <%= link_to "DeVaris Brown", "http://thefuriousone.com" %>
    </small>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner tk-museo-slab">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Zassman", root_path, class: "brand tk-museo-slab" %>
      <%= form_tag search_assets_path, :method => :get, :class => "navbar-search pull-left" do %>
        <%= text_field_tag :q, params[:q], :class => 'search-query', :placeholder => "Search by asset name or tag" %>
      <% end %>
      <div class="nav-collapse">
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to "Add Asset", new_asset_path %></li>
            <li><%= link_to "Activities", activities_path %></li>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown">Settings <strong class="caret"></strong></a>
              <ul class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In <strong class="caret"></strong></a>
              <!-- <li><%= link_to "Sign In", new_user_session_path %></li> -->
              <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
                <!-- Login form here -->
                <%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), html: { class: 'form-group'}) do |f| %>
                    <%= f.input :email, label: "Email" %>
                    <%= f.input :password, label: "Password" %>
                    <%= f.input :remember_me, as: :boolean, label: "Remember Me" %>

                    <%= f.submit "Sign in", class: "btn btn-primary" %> or <%= link_to image_tag("google.png"), user_omniauth_authorize_path(:google_oauth2) %>
                  <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zassman</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= typekit_include_tag "dex7uny" %>
    <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <%= render partial: "layouts/flash_messages", flash: flash %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    
  </body>
</html>